name: syncGitlab

on: 
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - name: Wait for flarum-bot to commit
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: master
        check-name: 'Build JavaScript assets'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    - uses: wangchucheng/git-repo-sync@master
      with:
        target-url: 'https://gitlab.com/huoxin/auto-collapse-long-images.git'
        target-username: 'huoxin'
        target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
